### ISSUE TITLE
Design Uniformation on UI  ( Web <> App )

### ISSUE THREAD

**Issue by hubtwork** [Hubtwork/JunctionX2021#13]
Needs to talk with for UI uniformation.

- check and talk with designer

**Comment by SeoungJinKim** [comment]
Okay Let's talk 4:00 pm 5/22

**Comment by hubtwork** [comment]
Again sink with meeting needed.
please comment it or send chat to me

**Comment by hubtwork** [comment]
UI Variation completed.
